[phases.setup]
nixPkgs = ["python310"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "playwright install-deps chromium",
  "playwright install chromium"
]

[start]
cmd = "streamlit run dashboard.py --server.port $PORT --server.address 0.0.0.0"
